"""报告模板.

提供 Markdown、HTML、JSON 等格式的报告模板.
"""
# ruff: noqa: W291  # 模板中的行尾空格是 markdown 语法的一部分

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum


class ReportFormat(Enum):
    """报告格式."""

    MARKDOWN = "markdown"
    JSON = "json"
    HTML = "html"


@dataclass
class ReportTheme:
    """报告主题配置."""

    # 颜色
    primary_color: str = "#0366d6"
    success_color: str = "#28a745"
    warning_color: str = "#ffc107"
    danger_color: str = "#dc3545"
    info_color: str = "#17a2b8"

    # 图标
    icon_success: str = "✅"
    icon_warning: str = "⚠️"
    icon_danger: str = "❌"
    icon_info: str = "ℹ️"


class MarkdownTemplates:
    """Markdown 报告模板."""

    # 报告头部
    HEADER = """# 🔍 ConsistenCy Code Health Report

> **Project**: {project_name}  
> **Scan Date**: {scan_date}  
> **Duration**: {duration:.2f}s  
> **Commit**: `{commit_sha}`

---

## 📊 Executive Summary

{summary}

### Severity Distribution

| Severity | Count | Icon |
|----------|-------|------|
| 🔴 Critical | {critical_count} | {icon_critical} |
| 🟠 High | {high_count} | {icon_high} |
| 🟡 Medium | {medium_count} | {icon_medium} |
| 🟢 Low | {low_count} | {icon_low} |
| ⚪ Info | {info_count} | {icon_info} |

**Total Issues**: {total_issues}

---
"""

    # 扫描器结果
    SCANNER_SECTION = """## 🔬 {scanner_name}

**Status**: {status}  
**Files Scanned**: {scanned_files}  
**Issues Found**: {issue_count}

{findings_table}

---
"""

    # 发现表格
    FINDINGS_TABLE = """### Findings

| Severity | File | Line | Rule | Message |
|----------|------|------|------|---------|
{rows}
"""

    TABLE_ROW = "| {severity} | `{file}` | {line} | `{rule}` | {message} |"

    # 详细发现
    FINDING_DETAIL = """### {severity} {rule_id}

**File**: `{file_path}`  
**Line**: {line}  
**Confidence**: {confidence:.0%}

{message}

{suggestion}

```
{code_snippet}
```

**Metadata**:
```json
{metadata}
```

---
"""

    # AI 审查部分
    AI_REVIEW_SECTION = """## 🤖 AI Code Review

### Summary

{summary}

**Overall Severity**: {severity}

### Comments

{comments}

### Action Items

{action_items}

---
"""

    AI_COMMENT = """#### {category} [{severity}]

**Location**: `{location}`

{message}

{suggestion}
"""

    # 技术债务热点
    HOTSPOT_SECTION = """## 🔥 Technical Debt Hotspots

| Rank | File | Complexity | Churn | Score | Risk |
|------|------|------------|-------|-------|------|
{rows}

**Legend**: Score = Complexity × Change Frequency

---
"""

    HOTSPOT_ROW = "| {rank} | `{file}` | {complexity:.1f} | {churn} | {score:.1f} | {risk} |"

    # 一致性漂移
    DRIFT_SECTION = """## 🔄 Consistency Drifts

| Pattern Type | File | Line | Observed | Expected | Confidence |
|--------------|------|------|----------|----------|------------|
{rows}

---
"""

    DRIFT_ROW = "| {pattern} | `{file}` | {line} | `{observed}` | `{expected}` | {confidence:.0%} |"

    # 页脚
    FOOTER = """---

*Generated by [ConsistenCy](https://github.com/consistancy-team/consistancy) v{version}*

**Need Help?**
- 📖 [Documentation](https://docs.consistancy.dev)
- 🐛 [Report Issues](https://github.com/consistancy-team/consistancy/issues)
"""


class HTMLTemplates:
    """HTML 报告模板."""

    # 完整 HTML 页面
    FULL_PAGE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ConsistenCy Report - {project_name}</title>
    <style>
        {css}
    </style>
</head>
<body>
    <div class="container">
        {content}
    </div>
</body>
</html>
"""

    # CSS 样式
    CSS = """
:root {
    --primary: #0366d6;
    --success: #28a745;
    --warning: #ffc107;
    --danger: #dc3545;
    --info: #17a2b8;
    --bg: #f6f8fa;
    --text: #24292e;
}

* { box-sizing: border-box; }

body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    line-height: 1.6;
    color: var(--text);
    background: var(--bg);
    margin: 0;
    padding: 20px;
}

.container {
    max-width: 1200px;
    margin: 0 auto;
    background: white;
    padding: 40px;
    border-radius: 8px;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}

h1 { color: var(--primary); border-bottom: 2px solid var(--primary); padding-bottom: 10px; }
h2 { margin-top: 40px; color: var(--text); }
h3 { margin-top: 30px; }

.severity-critical { color: var(--danger); font-weight: bold; }
.severity-high { color: #d73a49; font-weight: bold; }
.severity-medium { color: var(--warning); }
.severity-low { color: var(--success); }
.severity-info { color: var(--info); }

table {
    width: 100%;
    border-collapse: collapse;
    margin: 20px 0;
}

th, td {
    padding: 12px;
    text-align: left;
    border-bottom: 1px solid #e1e4e8;
}

th {
    background: var(--bg);
    font-weight: 600;
}

code {
    background: #f3f4f6;
    padding: 2px 6px;
    border-radius: 3px;
    font-family: 'SF Mono', Monaco, monospace;
    font-size: 0.9em;
}

pre {
    background: #f6f8fa;
    padding: 16px;
    border-radius: 6px;
    overflow-x: auto;
}

pre code {
    background: none;
    padding: 0;
}

.badge {
    display: inline-block;
    padding: 4px 8px;
    border-radius: 12px;
    font-size: 12px;
    font-weight: 600;
}

.badge-critical { background: #ffeef0; color: #86181d; }
.badge-high { background: #fff5f5; color: #c53030; }
.badge-medium { background: #fffaf0; color: #c05621; }
.badge-low { background: #f0fff4; color: #276749; }

.summary-box {
    background: var(--bg);
    padding: 20px;
    border-radius: 6px;
    margin: 20px 0;
}
"""

    # 头部
    HEADER = """
<div class="header">
    <h1>🔍 ConsistenCy Code Health Report</h1>
    <p><strong>Project</strong>: {project_name}</p>
    <p><strong>Scan Date</strong>: {scan_date}</p>
    <p><strong>Duration</strong>: {duration:.2f}s</p>
</div>

<div class="summary-box">
    <h2>Executive Summary</h2>
    {summary}
    <p><strong>Total Issues</strong>: <span class="badge badge-{worst_severity}">{total_issues}</span></p>
</div>
"""

    # 表格
    TABLE = """
<h3>{title}</h3>
<table>
    <thead>
        <tr>{headers}</tr>
    </thead>
    <tbody>
        {rows}
    </tbody>
</table>
"""

    TABLE_HEADER = "<th>{text}</th>"
    TABLE_ROW = "<tr>{cells}</tr>"
    TABLE_CELL = "<td>{text}</td>"


class JSONTemplates:
    """JSON 报告模板."""

    SCHEMA = """{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ConsistenCy Report",
    "type": "object",
    "properties": {
        "version": {"type": "string"},
        "scan_date": {"type": "string", "format": "date-time"},
        "project_name": {"type": "string"},
        "summary": {
            "type": "object",
            "properties": {
                "total_issues": {"type": "integer"},
                "severity_counts": {"type": "object"},
                "duration_ms": {"type": "number"}
            }
        },
        "scanners": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {"type": "string"},
                    "findings": {"type": "array"}
                }
            }
        },
        "ai_review": {"type": "object"}
    }
}"""
